Repository axleus/axleus-configmanager, pull requests merged in 2024-11, with the labels that each got.

#2 Create ConfigProvider
  src/ConfigProvider.php
Labels: enhancement, priority: Critical

#6 Signed-off-by: Joey Smith <jsmith@webinertia.net>
  src/ConfigManager.php
Labels: BugFix, priority: Critical, status: Confirmed

#5 Add onLoadConfig and onBustCache methods
  src/ConfigManager.php
  src/Event/ConfigEvent.php
Labels: New Feature, enhancement, priority: High
